version: 2.1
jobs:
  setup:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
        command: composer install
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
        command: npm run build
workflows:
  version: 2
  build:
    jobs:
      - setup
      - build
