version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - run:
      command: |
        npm i
        composer install
        npm run build
workflows:
  version: 2
  build:
    jobs:
    - build
