version: 2.1
orbs:
  jobs:
    build:
      steps:
      - run:
        command: |
          npm i
          composer install
          npm run build
workflows:
  version: 2
  build:
    jobs:
    - build
